### PR TITLE
add services and buttons to control the printer remotely

### PR DESCRIPTION
**Pull request by yohaybn**
add new services for abort, print and stop the printer.
also add service to get the files that stored on printer for remote printing

Added new buttons and select entity

### CODE REVIEW

**Comment by joseffallman** [comment]
Nice work!

Some quick thoughts.
- Perhaps rename "play" button to "Continue" ? Because it won't do anything if the print is not in paused mode.
- Rename "print" button to something to make it clear that the printer will start print selected file. ("Print file") ?
- Remove underscore in the name-field in Services.yaml, and all name start with capital letter, that will make it look better in the developer tools.

Thanks a lot for this pr, really great to have the functionality in HA.

**Comment by yohaybn** [comment]
Hi.
I fixed it... can you take a look?
thank you for your awesome work with library and this integration!

**Comment by joseffallman** [comment]
I made some changes, mostly linting. But also, moved mac an serial to device info instead of separate sensors. And created a separate FilePrinterButton class. It's ridiculous hard to get from a unique id to the state of that entity :)

Noticed that the file selector is only updated on home assistant restarts. And that's not so good. Could we use the FlashForgeDataUpdateCoordinator some how to query the printer about files and do the updates?

(Apologize if I force pushed but did a rebase to catch up)

//Josef

**Comment by yohaybn** [comment]
I added method to select entity that update the list.
I don't know if this method called automatically but when you call to homeassistant.update_entity service the list updated.

**Pull request merged**
